<?php if ($this->getNotificationPopupEnable()): ?>
<?php if ($content = $block->getContent('women-block')) { ?>
<!-- add your custom block_id above -->

<div id="modal-overlay" style="display:none;">
	<?php echo $content; ?>
</div>

<script type="text/x-magento-init">
	{
		"*": {
			"Magento_Ui/js/core/app": {
				"components": {
					"modal_overlay": {
						"component": "Shiv_PopupBlock/js/modal_overlay"
					}
				}
			}
		}
	}
</script>
<?php } ?>
<?php endif; ?>
